local Config = {
    TargetAim = {
        Enabled = false,
        Target = "None",
        AutoSelect = false,
        AutoFire = false,
        Strafe = false,
        ToggleStrafe = false,
        VisualizeStrafe = false,
        VisualizeStrafeInlineColor = Color3.fromRGB(255, 255, 255),
        VisualizeStrafeOutlineColor = Color3.fromRGB(255, 255, 255),
        StrafeMethod = "Randomize",
        StrafePrediction = 0.1,
        Highlight = false,
        HighlightOutlineColor = Color3.fromRGB(255, 255, 255),
        Tracer = false,
        TracerPosition = "Mouse",
        TracerFillColor = Color3.fromRGB(0, 200, 140),
        TracerOutlineColor = Color3.fromRGB(0, 0, 0),
        LookAt = false,
        SpectateTarget = false,
        AutoStomp = false,
        Prediction = 0,
        AutoPredict = false,
        PredictMode = "",
        HitPart = "Head",
        Offset = 0,
        JumpOffset = 0,
        AirPartEnabled = false,
        AirPart = "Head",
        Resolver = false,
        TargetStats = false,
        Autokill = false,
        DotCircle = false,
        Spoofer = false,
    },
    HitEffects = {
        HitSounds = false,
        HitSoundID = "rbxassetid://6534948092",
        HitSoundVolume = 5,
        HitNotifications = false,
        HitNotificationsTime = 3,
        HitChams = {
            Enabled = false,
            Color = Color3.fromRGB(255, 255, 255),
            Lifetime = 3,
            Transparency = 0.7,
            Material = "Neon",
        },
        HitEffect = {
            Enabled = false,
            Type = "Coom",
            Color = Color3.fromRGB(255, 255, 255),
        },
        HitSkeleton = {
            Enabled = false,
            Color = Color3.fromRGB(255, 255, 255),
        },
    },
    Checks = {
        Wall = false,
        Forcefield = false,
        Alive = false,
        Team = false,
    },
    KillAura = {
        Enabled = false,
        Active = false,
        Range = 250,
        Silent = false,
        Visualize = false,
        StompAura = false,
        Whitelist = {},
    },
    RapidFire = { Enabled = false },
    Wallbang  = { Enabled = false },
    HitboxExpander = {
        Enabled = false,
        Visualize = false,
        Color = Color3.fromRGB(255, 255, 255),
        OutlineColor = Color3.fromRGB(255, 255, 255),
        FillTransparency = 0.5,
        OutlineTransparency = 0.3,
        Size = 15,
    },
    Movement = {
        WalkSpeedEnabled = false,
        WalkSpeed = 16,
        JumpPowerEnabled = false,
        JumpPower = 50,
    },
    Desync = {
        Enabled = false,
        Mode = "Custom",
        RandomAmount = 20,
        Visualize = false,
        Line = false,
        Status = false,
        Dot = false,
        CustomX = 0,
        CustomY = 0,
        CustomZ = 0,
    },
    FakePos = {
        Enabled = false,
        Mode = "Voidless",
        Version = "Version 1",
        ReturnDelay = 0.5,
        Method = "Advanced",
        OriginalPos = nil,
        Active = false,
    },
    VelocitySpoofer = false,
    DirectionToShoot = "Custom",
    Direction = Vector3.zero,
    CustomVelocity = Vector3.zero,
    BulletTracers = {
        Enabled = false,
        TextureID = "rbxassetid://12781852245",
        Color = Color3.fromRGB(255, 255, 255),
        Size = 0.4,
        Transparency = 0,
        TimeAlive = 3,
    },
    Triggerbot = {
        Enabled = false,
        FOV = 20,
        Delay = 0,
        OnlyTarget = false,
        CheckKO = false,
        CheckKnife = false,
        CheckGrab = false,
        CheckTeam = false,
        CheckFriend = false,
        SelectedHitParts = {
            "Head", "HumanoidRootPart", "UpperTorso", "LowerTorso",
            "LeftUpperArm", "RightUpperArm", "LeftLowerArm", "RightLowerArm",
            "LeftHand", "RightHand", "LeftUpperLeg", "RightUpperLeg",
            "LeftLowerLeg", "RightLowerLeg", "LeftFoot", "RightFoot",
        },
    },
    Aimlock = {
        Enabled = false,
        HitPart = "Head",
        Smoothing = false,
        SmoothingAmount = 0.1,
        Prediction = 0.05,
        JumpOffset = 0,
        Offset = true,
        Resolver = false,
    },
    AutoBuy = {
        SelectedGun = "[Rifle]",
        AutoLoadout = false,
        AutoLoadoutGun = "[Rifle]",
        AutoHeal = false,
        AutoHealThreshold = 99,
        AutoArmor = false,
        AutoArmorThreshold = 50,
        AutoMask = false,
        SelectedMask = "surgeon",
    },
    Watermark = {
        Enabled = true,
        ShowFPS = true,
        ShowPing = true,
        ShowGameName = false,
        ShowUptime = false,
        ShowExecutor = false,
    },
    Menu = {
        NotifySide = "Right",
        DPI = 100,
        Keybind = "RightShift",
    },
    AntiAFK = false,
    InfiniteZoom = false,
    ChatSpy = true,
    NoJumpCooldown = false,
    Noclip = false,
    AntiVoid = true,
    AntiStomp = false,
    Flashback = false,
    AntiBag = false,
    AntiGrab = false,
    AutoReload = false,
    AntiRPGDesync = false,
    GrenadeDetection = false,
}

return Config